name: Round 2

on:
  push:
    branches: [round-2]

jobs: 
  Score:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: '0'
    - name: Setup Maven
      if: always()
      run: |
        sudo apt-get install default-jre
        sudo apt-get install default-jdk
        sudo apt-get install maven
    - name: Setup Python
      if: always()
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6
    - name: Set up golfing environment
      run: |
        sudo apt-get update
        sudo python -m pip install --upgrade pip
        sudo python -m pip install gatorgrade --ignore-installed PyYAML
      if: always()
    - name: Score Round 2
      id: score
      run: |
        export PAR=218
        export BYTE_SCORE=$(wc -c 2/src/test/resources/main.lox | awk '{print $1}')
        export DIFFERENCE=$((BYTE_SCORE-PAR))
        gatorgrade --config gatorgrade.yml --report file json gatorgrade_summary.json
        cat > $GITHUB_STEP_SUMMARY << EOF 
        ![Score: $(echo $BYTE_SCORE) bytes](https://img.shields.io/badge/Score-$(echo $BYTE_SCORE)_bytes_($DIFFERENCE)-green)
        EOF
        if [ $DIFFERENCE -eq 0 ]; then echo "[ERROR] ROUND HAS NOT BEEN PLAYED!"; fi
      if: always()
      env:   
        PIPENV_VENV_IN_PROJECT: 1
        PIPENV_IGNORE_VIRTUALENVS: 1
